export const GET_DEVICES = 'GET_DEVICES';
export const GET_UPDATED_DEVICES = 'GET_UPDATED_DEVICES';
export const GET_REDUCED_DEVICES = 'GET_REDUCED_DEVICES';
export const GET_DIVERSIFIED_DEVICES = 'GET_DIVERSIFIED_DEVICES';
export const CLEAR_ERROR = 'CLEAR_ERROR';
